function [f,Df] = f_numFileWithDerivative(in1,in2)
%f_numFileWithDerivative
%    [F,Df] = f_numFileWithDerivative(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    08-Sep-2022 22:44:17

x0_1 = in2(1,:);
x0_2 = in2(2,:);
x_1 = in1(1,:);
x_2 = in1(2,:);
t2 = x0_1-x_1;
t3 = x0_2-x_2;
f = [t2.^2;t3.^2];
if nargout > 1
    Df = reshape([t2.*-2.0,0.0,0.0,t3.*-2.0],[2,2]);
end
